#!/bin/bash
# Script 5: Open Source Manifesto Generator
# Author: Arpit Raj Singh | Course: Open Source Software
# Purpose: Generate a personalised open source philosophy statement
#          by asking the user three questions interactively and saving
#          the result to a text file.

# --- Alias concept demonstration (comment) ---
# In an interactive bash session, you could define:
#   alias manifesto='bash script5_manifesto_generator.sh'
# Aliases are shorthand commands that expand to longer strings.
# We demonstrate the concept here in a comment as scripts don't persist aliases.

echo "========================================================"
echo "       THE OPEN SOURCE MANIFESTO GENERATOR"
echo "========================================================"
echo "  Answer the questions below to generate your manifesto."
echo "========================================================"
echo ""

# --- Collect user input interactively using read -p ---
read -p "1. Name one open-source tool you use every day: " TOOL
read -p "2. In one word, what does 'freedom' mean to you in software? " FREEDOM
read -p "3. Name one thing you would build and share freely with the world: " BUILD
read -p "4. Your name (for the manifesto signature): " NAME

# --- Use the date command to get the current date and time ---
DATE=$(date '+%d %B %Y')
TIME=$(date '+%H:%M')

# --- Build the output filename using string concatenation and whoami ---
OUTPUT="manifesto_$(whoami).txt"

echo ""
echo "Composing your manifesto..."
echo ""

# --- Write the file header using > (creates or overwrites the file) ---
echo "=======================================================" > "$OUTPUT"
echo "         OPEN SOURCE MANIFESTO"                         >> "$OUTPUT"
echo "         Written by: $NAME"                             >> "$OUTPUT"
echo "         Date: $DATE at $TIME"                          >> "$OUTPUT"
echo "=======================================================" >> "$OUTPUT"
echo ""                                                        >> "$OUTPUT"

# --- Compose the manifesto body using a heredoc (<<EOF) with variable substitution ---
# The heredoc writes multiple lines to the file in one block
cat >> "$OUTPUT" << EOF
I am a person who uses $TOOL every day — a tool I did not build alone,
but one that thousands of people around the world chose to share freely.
They did not have to. They chose to.

To me, freedom in software means $FREEDOM. Not as an abstraction,
but as a lived reality: the freedom to look inside the tools I depend on,
to understand them, to improve them, and to pass them on.

Linus Torvalds was a student who could not afford a Unix system. Richard
Stallman watched a printer fail and could not fix it because the code was
locked. The people who built the tools I use every day faced those same
walls — and instead of accepting them, they built doors.

One day, I want to build $BUILD and release it freely.
Not because the license requires it. Because I understand now what it means
to stand on the shoulders of those who built in the open before me.

This is my commitment to open source.

— $NAME, $DATE
EOF

# --- Append a closing separator using >> ---
echo ""                                                           >> "$OUTPUT"
echo "======================================================="    >> "$OUTPUT"
echo "  Generated by the OSS Capstone Manifesto Script"          >> "$OUTPUT"
echo "  Linux Kernel Audit | Course: Open Source Software"       >> "$OUTPUT"
echo "======================================================="    >> "$OUTPUT"

# --- Display the saved manifesto to the terminal using cat ---
echo "========================================================"
echo "  Manifesto saved to: $OUTPUT"
echo "========================================================"
echo ""
cat "$OUTPUT"
